name: FPL Minileague Data Pull

on:
  # Manual trigger
  workflow_dispatch: {}
  # Scheduled run (UTC). This runs daily at 07:10 UTC (~08:10 UK during BST).
  schedule:
    - cron: '10 7 * * *'

# Prevent overlapping runs if a previous one is still running.
concurrency:
  group: fpl-minileague
  cancel-in-progress: true

# Needed to push CSV updates back to the repo.
permissions:
  contents: write

env:
  PYTHONUNBUFFERED: '1'
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'   # cache pip downloads between runs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas tqdm

      - name: Run FPL pull
        # Assumes the script is at scripts/pull_fpl_league_picks.py
        run: |
          python pull_fpl_league_picks.py

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: fpl-picks-542663
          path: ./fpl_league_542663_picks_wide.csv
          if-no-files-found: warn

      - name: Move output to data/ folder
        run: |
          mkdir -p data
          mv -f fpl_league_542663_picks_wide.csv data/fpl_league_542663_picks_wide.csv

      - name: Commit & push CSV to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update: FPL picks CSV for league 542663"
          file_pattern: data/*.csv
