name: FPL Monthly Report

on:
  schedule:
    - cron: "0 0 1 * *"   # runs at 00:00 UTC on the 1st of every month
  workflow_dispatch:       # allows manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run FPL script
        run: python fplData.py

      - name: Commit report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add WWHALigaData.xlsx
          git commit -m "Update report [skip ci]" || echo "No changes"
          git push
